# Atividade da Disciplina Método númerico computacionais
Sistemas lineares

## Importando Libs


In [ ]:
# math
import numpy as np
from numpy.linalg import det
# styles
from termcolor import colored
#text
import re

## Criando a função `LinearSystemClassify`

In [ ]:
def LinearSystemClassify(vecValue):

  def title(text):
    print(colored(text, 'cyan', attrs=['bold']))
  def subtitle(text):
    text = "- " + text
    print(colored(text, 'cyan', attrs=['bold']))
  def division(text):
    print(colored(text, 'cyan', attrs=["underline"]))

  if isinstance(vecValue[0], list):
    #setting variables
    vecValue = np.array(vecValue) # full matrix vector values
    lenVecValue = len(vecValue)  # size of full vetor
    
    # coefficient matrix
    matrixCoef = np.delete(vecValue, lenVecValue-1, 0)

    # independent term array
    independentTerm = vecValue[lenVecValue-1] 
    
    # Creating a matrixCoefx
    
    # adding size shape reference
    matrixCoefx = np.array([independentTerm]) 
    
    # adding respective column and line
    for i in range(lenVecValue-1):
      line = list()

      for j in range(len(vecValue[i])):
        #create line values

        if(j == 0): 
          line.append(independentTerm[i]) # adding independent term how firs column in line
        else:
          line.append(matrixCoef[i][j]) # adding rest values
              
        if(j == len(vecValue[i])-1):
          matrixCoefx = np.vstack([matrixCoefx,line]) #adding line to matrixCoefx  

    #delete shape reference line
    matrixCoefx = np.delete(matrixCoefx, 0, 0)
  
  if isinstance(vecValue[0], str): # if is string input

    #matrixCoef;
    independentTerm = list();

    for i in range(len(vecValue)):
      equation = i;


      #removing spaces
      spaceRemoved = re.sub(r"\s+", "", vecValue[equation]) 

      # split coefficients and indepedent terms
      splitText = re.split(r'([\=])', spaceRemoved) 

      #get indenpent value in equation
      independentTerm.append(eval(splitText[len(splitText) -1]))
      

      matrixCoefxMaker = re.split(r'([\w])', splitText[0])
      
      line = list()
      signal = 1;
      number = False;
      
      for i in range(len(matrixCoefxMaker)):
        if re.search(r"([\d,.])",matrixCoefxMaker[i]):
          if(number == False):
            number = matrixCoefxMaker[i];
          else:
            number = number + matrixCoefxMaker[i]

        elif (matrixCoefxMaker[i] == "-"):
          #print(matrixCoefxMaker[i] + " is minus");
          signal = -1;
        
        elif re.search(r"([\w])",matrixCoefxMaker[i]):
          #print(matrixCoefxMaker[i] + " is world");
          if(type(number) != bool):
            number = eval(number)

            line.append(number*signal)
            signal = 1;
            number = False;   
          
          else: # number hidden
            number = 1;

            line.append(number*signal)
            signal = 1;
            number = False;  

      if (equation == 0):
        matrixCoef = np.array(line)  
      
      else:
        matrixCoef = np.vstack([matrixCoef,line]) #adding line to matrixCoef  
  


  # adding size shape reference
  matrixCoefx = np.array([independentTerm]) 
  
  # adding respective column and line
  for i in range(len(matrixCoef)):
    line = list()

    for j in range(len(independentTerm)):
      #create line values

      if(j == 0): 
        line.append(independentTerm[i]) # adding independent term how firs column in line
      else:
        line.append(matrixCoef[i][j]) # adding rest values
            
      if(j == len(independentTerm) -1):
        matrixCoefx = np.vstack([matrixCoefx,line]) #adding line to matrixCoefx  

  #delete shape reference line
  matrixCoefx = np.delete(matrixCoefx, 0, 0)
   
  title("\n----------LinearSytemClassify----------\n")
  subtitle("Matriz dos coeficientes:\n")
  print(matrixCoef)
  division("                        \n")
  subtitle("O termo independente é:\n")
  print(independentTerm)
  division("                         \n")
  subtitle("Matriz para a variavel x:\n")
  print(matrixCoefx)
  division("                         \n")
  
  #solve Linear system
  subtitle("Classificação:\n")
  detMatrixCoef = np.linalg.det(matrixCoef)
  detMatrixCoefx = np.linalg.det(matrixCoefx)

  if detMatrixCoef !=0: 
    solve = np.linalg.solve(matrixCoef,independentTerm)  # solving linear system if is be possible and determined
    print("SPD: Sistema Possivel Determinado,\n sendo sua solução:\n", solve)

  else:
    if detMatrixCoef ==0 and detMatrixCoefx ==0:
      print("SPI: Sistema Possivel e Indeterminado")
    else:
      print("SI: Sistema Impossivel")
  title("\n------------------//-------------------\n")

## Exercicios

$$
1.
\begin{cases}
2a-b=5 \\
a-2b=10
\end{cases}
$$

In [ ]:
LinearSystemClassify(["2a-b=5", "4a-2b=10"])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 2 -1]
 [ 4 -2]]
                        

- O termo independente é:

[5, 10]
                         

- Matriz para a variavel x:

[[ 5 -1]
 [10 -2]]
                         

- Classificação:

SPI: Sistema Possivel e Indeterminado

------------------//-------------------



2. Escreva a equação do sistema associada à matriz dada. Resolver o sistema.

$$
\begin{bmatrix}
-4 & 1 &  0 \\
3  & 5 & -2 \\
1  & 0 &  6 \\
\end{bmatrix}.\begin{bmatrix}
m  \\
n  \\
p  \\
\end{bmatrix} = \begin{bmatrix}
1  \\
2  \\
3  \\
\end{bmatrix}
$$

A matriz é associda ao sistema linear:

$$
\begin{cases}
-4m+1n=1 \\
3m+5n-2p=2 \\
m+6p=3
\end{cases}
$$

In [ ]:
LinearSystemClassify(["-4m+1n+0p=1", "3m+5n-2p=2", "m+0n+6p=3"])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[-4  1  0]
 [ 3  5 -2]
 [ 1  0  6]]
                        

- O termo independente é:

[1, 2, 3]
                         

- Matriz para a variavel x:

[[ 1  1  0]
 [ 2  5 -2]
 [ 3  0  6]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [-0.08571429  0.65714286  0.51428571]

------------------//-------------------



3.Resolver por escalonamento

$$
\begin{cases}
x+2y+4z=5 \\
2x-y-2z=8 \\
3x-3y-z=7
\end{cases}
$$

$$
\begin{bmatrix}
1 &  2 &  4 \\
2 & -1 &  2 \\
3 & -3 & -1 \\
\end{bmatrix}.\begin{bmatrix}
x  \\
y  \\
z  \\
\end{bmatrix} = \begin{bmatrix}
5  \\
8  \\
7  \\
\end{bmatrix}
$$

In [ ]:
LinearSystemClassify([[1,2,4], [2,-1,2], [3, -3, -1], [5,8,7]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 1  2  4]
 [ 2 -1  2]
 [ 3 -3 -1]]
                        

- O termo independente é:

[5 8 7]
                         

- Matriz para a variavel x:

[[ 5  2  4]
 [ 8 -1  2]
 [ 7 -3 -1]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [ 1. -2.  2.]

------------------//-------------------



4.Resolver o sistema

$$
\begin{cases}
x+2y-z=8  \\
2x+3y+z=1 \\
5x+3y-2z=-11
\end{cases}
$$

In [ ]:
LinearSystemClassify(["x+2y-z=8", "2x+3y+z=1", "5x+3y-2z=-11"])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 1  2 -1]
 [ 2  3  1]
 [ 5  3 -2]]
                        

- O termo independente é:

[8, 1, -11]
                         

- Matriz para a variavel x:

[[  8   2  -1]
 [  1   3   1]
 [-11   3  -2]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [-7.  6. -3.]

------------------//-------------------



5.Um clube de investimento tem um
montante em dinheiro para investimentos
em ações.

Para aceitar um risco relativo, os formadores do
fundo decidiram dividir os investimentos em
**alto risco (x)**, **médio risco (y)** e **baixo risco (z)**.

O fundo estima um retorno ao ano de **15% para
ações de alto risco**, **10% para ações de médio
risco** e **6% para ações de baixo risco**.

Os membros decidiram que
investimentos de **baixo risco** devem ser
igual a soma das outras duas categorias.

Determinar quanto o clube deve investir em cada
tipo de ação seguindo o seguinte cenário:

O clube tem **R$ 200.000,00** para investir.

O objetivo é ter um retorno de **R$ 20.000,00** ao ano
sobre o total de investimentos.

 **<u>Solução:</u>**
 - 15% = 0.15 -> x
 - 10% = 0.1 -> y
 - 6% = 0.06 -> z

 $$
 0.15x+0.1y+0.06z=20000
 $$

_"investimentos de baixo risco **(z)** devem ser igual a soma das outras duas categorias **(x,y)**"_
 
 $$x+y-z=0$$

 _O clube tem **R$ 200.000,00** para investir_
 $$x+y+z=200000$$

Então o sistema linear fica:

 $$
 \begin{cases}
 0.15x+0.1y+0.06z=20000 \\
 x+y-z=0 \\
 x+y+z=200000
 \end{cases}
 $$

In [ ]:
LinearSystemClassify(["0.15x+0.1y+0.06z=20000", "x+y-z=0", "x+y+z=200000"])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 0.15  0.1   0.06]
 [ 1.    1.   -1.  ]
 [ 1.    1.    1.  ]]
                        

- O termo independente é:

[20000, 0, 200000]
                         

- Matriz para a variavel x:

[[ 2.e+04  1.e-01  6.e-02]
 [ 0.e+00  1.e+00 -1.e+00]
 [ 2.e+05  1.e+00  1.e+00]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [ 80000.  20000. 100000.]

------------------//-------------------



- **80000** é a quantidade para o ser investido a X(*alto risco*)
- **20000** é a quantidade para o ser investido a Y(*Médio risco*)
- **100000** é a quantidade para o ser investido a **Z**(*baixo risco*)

