# Atividade da Disciplina Método númerico computacionais

## Sistemas lineares

Resolver e classificar cada sistema linear em **_SPD_**, **_SPI_** , **_SI_**

## Importando Libs






In [123]:
# math
import numpy as np
from numpy.linalg import det
# styles
from termcolor import colored

## Funções para estilização

In [124]:
def title(text):
  print(colored(text, 'cyan', attrs=['bold']))
def subtitle(text):
  text = "- " + text
  print(colored(text, 'cyan', attrs=['bold']))
def division(text):
  print(colored(text, 'cyan', attrs=["underline"]))

## Criando a função `LinearSystemClassify`

Essa função classifica os sistema lineares se é:

- **SPD** (*Sistema Possível Determinado*)
- **SPI** (*Sistema Possível e Indeterminado*)
- **SI** (*Sistema Impossível*)

E recebe como parametro um array, contendo os valores dos coeficientes e dos termos indenpedentes e a própria função separa os termos e gera as matrizes respectivas para a classificação. caso o sistema linear for **SPD**, ele irá mostrar a solução do mesmo.  

In [125]:
def LinearSystemClassify(vecValue):
  
  #setting variables
  vecValue = np.array(vecValue) # full matrix vector values
  lenVecValue = len(vecValue)  # size of full vetor
  
  # coefficient matrix
  matrixCoef = np.delete(vecValue, lenVecValue-1, 0)

  # independent term array
  independentTerm = vecValue[lenVecValue-1] 
  
  # Creating a matrixCoefx
  
  # adding size shape reference
  matrixCoefx = np.array([independentTerm]) 
  
  # adding respective column and line
  for i in range(lenVecValue-1):
     line = list()

     for j in range(len(vecValue[i])):
       #create line values

       if(j == 0): 
        line.append(independentTerm[i]) # adding independent term how firs column in line
       else:
         line.append(matrixCoef[i][j]) # adding rest values
            
       if(j == len(vecValue[i])-1):
         matrixCoefx = np.vstack([matrixCoefx,line]) #adding line to matrixCoefx  

  #delete shape reference line
  matrixCoefx = np.delete(matrixCoefx, 0, 0)


  
  title("\n----------LinearSytemClassify----------\n")
  subtitle("Matriz dos coeficientes:\n")
  print(matrixCoef)
  division("                        \n")
  subtitle("O termo independente é:\n")
  print(independentTerm)
  division("                         \n")
  subtitle("Matriz para a variavel x:\n")
  print(matrixCoefx)
  division("                         \n")
  
  #solve Linear system
  subtitle("Classificação:\n")
  detMatrixCoef = np.linalg.det(matrixCoef)
  detMatrixCoefx = np.linalg.det(matrixCoefx)

  if detMatrixCoef !=0: 
    solve = np.linalg.solve(matrixCoef,independentTerm)  # solving linear sytem if will be possible and determined
    print("SPD: Sistema Possivel Determinado,\n sendo sua solução:\n", solve)

  else:
    if detMatrixCoef ==0 and detMatrixCoefx ==0:
      print("SPI: Sistema Possivel e Indeterminado")
    else:
      print("SI: Sistema Impossivel")
  title("\n------------------//-------------------\n")

## Exercicios

$$
1. 
\begin{cases}
2x-y=7 \\
x+5y=-2
\end{cases}
$$

In [126]:
LinearSystemClassify([[2,-1],[1,5],[7,-2]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 2 -1]
 [ 1  5]]
                        

- O termo independente é:

[ 7 -2]
                         

- Matriz para a variavel x:

[[ 7 -1]
 [-2  5]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [ 3. -1.]

------------------//-------------------



$$
2.
\begin{cases}
x+2y -z =0 \\
3x-4y+5z=10 \\
x+y+9z=1 
\end{cases}
$$

In [127]:
LinearSystemClassify([[1,2,-1],[3,-4,5],[1,1,9],[0,10,1]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 1  2 -1]
 [ 3 -4  5]
 [ 1  1  9]]
                        

- O termo independente é:

[ 0 10  1]
                         

- Matriz para a variavel x:

[[ 0  2 -1]
 [10 -4  5]
 [ 1  1  9]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [ 2.00000000e+00 -1.00000000e+00  4.82705663e-17]

------------------//-------------------



$$
3.
\begin{cases}
x+2y=5 \\
2x-3y=-4
\end{cases}
$$

In [128]:
LinearSystemClassify([[1,2],[2,-3],[5,-4]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 1  2]
 [ 2 -3]]
                        

- O termo independente é:

[ 5 -4]
                         

- Matriz para a variavel x:

[[ 5  2]
 [-4 -3]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [1. 2.]

------------------//-------------------



$$
4.
\begin{cases}
x+y=5 \\
2x+2y=10
\end{cases}
$$

In [129]:
LinearSystemClassify([[1,1],[2,2],[5,10]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[1 1]
 [2 2]]
                        

- O termo independente é:

[ 5 10]
                         

- Matriz para a variavel x:

[[ 5  1]
 [10  2]]
                         

- Classificação:

SPI: Sistema Possivel e Indeterminado

------------------//-------------------



$$
5.
\begin{cases}
2a-b+c=3 \\
a-b+2c=3 \\
a+b+c=6
\end{cases}
$$

In [130]:
LinearSystemClassify([[2,-1,1],[1,-1,2],[1,1,1],[3,3,6]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 2 -1  1]
 [ 1 -1  2]
 [ 1  1  1]]
                        

- O termo independente é:

[3 3 6]
                         

- Matriz para a variavel x:

[[ 3 -1  1]
 [ 3 -1  2]
 [ 6  1  1]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [1.8 2.4 1.8]

------------------//-------------------



$$
6.\begin{bmatrix}
1 & 4 & 7 \\
2 & 3 & 6 \\
5 & 1 & -1 \\
\end{bmatrix}.\begin{bmatrix}
x  \\
y  \\
z  \\
\end{bmatrix} = \begin{bmatrix}
2  \\
2  \\
8  \\
\end{bmatrix}
$$

In [131]:
LinearSystemClassify([[1,4,7],[2,3,6],[5,1,-1],[2,2,8]])


----------LinearSytemClassify----------

- Matriz dos coeficientes:

[[ 1  4  7]
 [ 2  3  6]
 [ 5  1 -1]]
                        

- O termo independente é:

[2 2 8]
                         

- Matriz para a variavel x:

[[ 2  4  7]
 [ 2  3  6]
 [ 8  1 -1]]
                         

- Classificação:

SPD: Sistema Possivel Determinado,
 sendo sua solução:
 [ 1.  2. -1.]

------------------//-------------------

